# Generated by Django 3.0.8 on 2020-07-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
