# Generated by Django 3.0.8 on 2020-07-23 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_products_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
